/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CHMIL Studio (https://sketchfab.com/chmilstudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chmil-mannequin-bust-2024-d5606415cb9e44009b562942b23e943f
Title: CHMIL Mannequin Bust 2024
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from '../assets/3d/chmil_mannequin_bust_2024.glb'
import { useFrame } from '@react-three/fiber';

export function Head(props) {
  const headRef = useRef();
  const { nodes, materials } = useGLTF(model)
 
  useFrame(({ clock }) => {
    if (headRef.current) {
      // Calculate rotation angle using sine wave
      let angle = Math.sin(clock.getElapsedTime()) * Math.PI / 2; // Adjust the amplitude as needed
      
      // Clamp rotation angle to be within -90 degrees to 90 degrees
      headRef.current.rotation.y = Math.max(-Math.PI / 2.5, Math.min(angle, Math.PI / 2.5));
    }
  });

  return (
    <group ref={headRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.final_for_upload_final_for_upload0_0.geometry}
          material={materials.final_for_upload0}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.1}
        />
      </group>
    </group>
  )
}

useGLTF.preload(model)
