name: Verify and build next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependecies
        run: npm install
      - name: build
        run: npm run build
      - name: upload static website
        uses: actions/upload-artifact@v2
        with:
          name: uuft-static
          path: out/
            
      
