name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 7
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:api"
        push: true
        tags: uugai/facialaccess-backend:${{ steps.short-sha.outputs.sha }}
